my_zoo_app/urls.py
from django.urls import path
from . import views # Import views to connect routes to view functions

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('animals/', views.animal_index, name='animal-index'),
    path('animals/<int:animal_id>/', views.animal_detail, name='animal-detail'),
    path('animals/create/', views.AnimalCreate.as_view(), name='animal-create'),
    path('animals/<int:pk>/update/', views.AnimalUpdate.as_view(), name='animal-update'),
    path('animals/<int:pk>/delete/', views.AnimalDelete.as_view(), name='animal-delete'),
    path(
        'animals/<int:animal_id>/add-status/',
        views.add_status,
        name='add-status'
    ),
    path('donations/create/', views.DonationCreate.as_view(), name='donation-create'),
    path('donations/<int:pk>/', views.DonationDetail.as_view(), name='donation-detail'),
    path('donations/', views.DonationList.as_view(), name='donation-index'),
    path('donations/<int:pk>/update/', views.DonationUpdate.as_view(), name='donation-update'),
    path('donations/<int:pk>/delete', views.DonationDelete.as_view(), name='donation-delete'),
    path('accounts/signup/', views.signup, name='signup'),

]

zootycoon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_zoo_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

my_zoo_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

CONSERVATION = (
    ('LR', 'Low Risk'),
    ('VR', 'Vulnerable'),
    ('ED', 'Endangered'),
    ('CE', 'Critically Endangered'),
)

# Create your models here.
class Donation(models.Model):
    donor = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.donor
    
    def get_absolute_url(self):
        return reverse('donation-detail', kwargs={'pk': self.id})

class Animal(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("animal-detail", kwargs={"animal_id": self.id})
    
    
class Conservation(models.Model):
    date = models.DateField('Date Changed')
    status=models.CharField(
        max_length=2,
        choices=CONSERVATION,
        default=CONSERVATION[0][0]
    )

    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_status_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

my_zoo_app/forms.py
from django import forms
from .models import Conservation

class ConservationForm(forms.ModelForm):
    class Meta:
        model = Conservation
        fields = ['date', 'status']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

my_zoo_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Animal, Donation
from .forms import ConservationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def animal_index(request):
    animals = Animal.objects.filter(user=request.user)
    return render(request, 'animals/index.html', {'animals': animals})

@login_required
def animal_detail(request, animal_id):
    animal = Animal.objects.get(id=animal_id)
    conservation_form = ConservationForm()
    return render(request, 'animals/detail.html', {
        'animal': animal, 'conservation_form': conservation_form
        })

@login_required
def add_status(request, animal_id):
    form = ConservationForm(request.POST)
    if form.is_valid():
        new_status = form.save(commit=False)
        new_status.animal_id = animal_id
        new_status.save()
    return redirect('animal-detail', animal_id=animal_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('animal-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)



class AnimalCreate(LoginRequiredMixin, CreateView):
    model = Animal
    fields = '__all__'
    success_url = '/animals/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class AnimalUpdate(LoginRequiredMixin, UpdateView):
    model = Animal
    fields = ['species', 'description', 'age']

class AnimalDelete(LoginRequiredMixin, DeleteView):
    model = Animal
    success_url = '/animals/'

class DonationCreate(LoginRequiredMixin, CreateView):
    model = Donation
    fields = '__all__'

class DonationList(LoginRequiredMixin, ListView):
    model = Donation

class DonationDetail(LoginRequiredMixin, DetailView):
    model = Donation

class DonationUpdate(LoginRequiredMixin, UpdateView):
    model = Donation
    fields = ['amount']

class DonationDelete(LoginRequiredMixin, DeleteView):
    model = Donation
    success_url = '/donations/'

my_zoo_app/templates/about.html
{% extends 'base.html' %} 
{% load static %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% block content %}
<h1>About Zoo Typhoon</h1>
<hr />
<p class="page-content">
<img id="zoo-photo" src="{% static 'images/zoo-photo.png' %}" width= 500px alt="Graphic of people at a zoo" />
  Zoo Typhoon is a way for you to keep track of your own digital zoo and the donations from visitors to each of your treasured animals! Log each one by name, age and even their conservation status so you can be up to date on saving the species!
</p>
{% endblock %}

my_zoo_app/templates/animals/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/animals/animal-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="animal-container">
  <div class="animal-img">
    <img id="animal-photo" src="{% static 'images/lion.jpg' %}" alt="A lion" />
  </div>
  <div class="animal-details">
    <h1>{{ animal.name }}</h1>
    {% if animal.age > 0 %}
      <h2>A {{ animal.age }} year old {{ animal.species }}</h2>
    {% else %}
      <h2>A {{ animal.species }}.</h2>
    {% endif %}
    <p>{{ animal.description }}</p>
    <div class="animal-actions">
      <a href="{% url 'animal-update' animal.id %}" class="btn warn">Edit</a>
      <a href="{% url 'animal-delete' animal.id %}" class="btn danger">Delete</a>
    </div>
  </div>

  <div class="conservation-donations-container">
    <section class="conservation">
      <div class="subsection-title">
        <h2>Conservation Status</h2>
        <img
          src="{% static 'images/elephant_icon.png' %}"
          alt="an icon of an elephant"
        />
        <img src="{% static 'images/leopard_icon.png' %}" alt="An icon of a leopard" />
        <img
          src="{% static 'images/crocodile_icon.png' %}"
          alt="An icon of a crocodile"
        />
      </div>

      <h3>Add Conservation Status</h3>
      <form
          action="{% url 'add-status' animal.id %}"
          method="post"
          class="subsection-content"
          autocomplete="off"
        >
        {% csrf_token %} 
        {{ conservation_form.as_p }}
        <button type="submit" class="btn submit">Add Status</button>
      </form>

      <h3>Conservation Status</h3>
{% if animal.conservation_set.all.count %}
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for conservation in animal.conservation_set.all %}
      <tr>
        <td>{{conservation.date}}</td>
        <td>{{conservation.get_status_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <div class="subsection-content">
    <p>⚠️ {{animal.name}} has not been updated!</p>
  </div>
{% endif %}
  
  {% endblock %}

my_zoo_app/templates/animals/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/animals/animal-index.css' %}"/>
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>Animal List 🐘🦓🦒🐅</h1>
</section>

<section class="card-container">
  {% for animal in animals %}
    <div class="card">
      <a href="{% url 'animal-detail' animal.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img
            class="card-img"
            src="{% static 'images/zebra.jpg' %}"
            alt="A zebra"
          />
        </div>
        <h2 class="card-title">{{ animal.name }}</h2>
        {% if animal.age > 0 %}
        <p>A {{ animal.age }} year old {{ animal.breed }}</p>
        {% else %}
        <p>A newborn {{ animal.breed }}.</p>
        {% endif %}
        <p><small>{{ animal.description }}</small></p>
        <p class="con-status"><large>{{ animal.status }}</large></p>
      </div>
    </div>
  {% endfor %}
</section>

{% endblock %}

my_zoo_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/zootyphoon-logo.png' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <title>Zoo Typhoon</title>
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img id="header-logo" src="{% static 'images/typhoon-logo.png' %}" width= 10% alt="The Zoo Typhoon Logo" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'animal-index' %}">All Animals</a></li>
          <li><a href="{% url 'donation-index' %}">All Donations</a></li>
          <li><a href="{% url 'animal-create' %}">Add an Animal</a></li>
          <li><a href="{% url 'donation-create' %}">Add a Donation</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit">Log out</button>
            </form>
          </li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

my_zoo_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<section class="logo-container">
    <img id="zoo-photo" src="{% static 'images/zoo-photo.png' %}" width= 500px alt="Graphic of people at a zoo" />
    <h1>Zoo Typhoon</h1>
  
</section>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

  

{% endblock %}

my_zoo_app/templates/my_zoo_app/animal_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Animal?</h1>
  <img src="{% static 'images/crocodile_icon.png' %}" alt="an icon of a crocodile" />
</div>

<h2>Are you sure you want to delete {{ animal.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'animal-detail' animal.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

my_zoo_app/templates/my_zoo_app/animal_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  {% if animal %}
    <h1>Edit {{ animal.name }}</h1>
  {% else %}
    <h1>Add an Animal</h1>
  {% endif %}
</div>


<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

my_zoo_app/templates/my_zoo_app/donation_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Remove Donation?</h1>
  <img src="{% static 'images/giving.png' %}" alt="A hand with a gold coin" />
</div>
<h2>Are you sure you want to remove ${{ object.amount }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'donation-detail' donation.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Remove!</button>
</form>

{% endblock %}

my_zoo_app/templates/my_zoo_app/donation_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/donations/donation-detail.css' %}" />
{% endblock %} 
{% block content %}

<div class="card" style="border-color: {{ green }}">
  <div class="card-bg" style="background-color: {{ green }}"></div>
  <div class="card-content">
    <h2>{{ donation.donor }}'s Donation</h2>
    <p>They gave ${{ donation.amount }} to support the zoo!</p>
  </div>
</div>
<a href="{% url 'donation-update' donation.id %}" class="btn warn">Edit</a>
<a href="{% url 'donation-delete' donation.id %}" class="btn danger">Delete</a>

{% endblock %}

my_zoo_app/templates/my_zoo_app/donation_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.donor}}'s Donation</h1>
    {% else %}
      <h1>Give a Donation</h1>
    {% endif %}
    <img src="{% static 'images/donation.png' %}" alt="A cat using a computer" />
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

my_zoo_app/templates/my_zoo_app/donation_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/toys/donation-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Donations</h1>
  <img src="{% static 'images/giving.png' %}" alt="A hand with a gold coin in it" />
</section>

<section class="card-container">
  {% for donation in donation_list %}
    <div class="card" style="border-color: {{ green }}">
      <div class="card-bg" style="background-color: {{ green }}"></div>
      <a href="{% url 'donation-detail' donation.id %}">
        <div class="card-content">
          <h2>{{ donation.donor }}</h2>
          <p>${{ donation.amount }}</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

my_zoo_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/elephant_icon.png' %}" alt="An elephant icon" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}